---
title: "Assembly analysis"
author: "Moray Smith"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(ggpubr)
```

```{r}
gc <- read_tsv("../results/windows/gc.bed", comment = "#", col_names = FALSE) |>
  select(chrom = X1, start = X2, end = X3, proportion = X5) |>
  mutate(feature = "GC")

genes <- read_tsv(
  "../results/windows/genes.bed",
  comment = "#",
  col_names = FALSE
  ) |>
  select(chrom = X1, start = X2, end = X3, proportion = X7) |>
  mutate(feature = "genes")

ty1 <- read_tsv(
  "../results/windows/Ty1.bed",
  comment = "#",
  col_names = FALSE
  ) |>
  select(chrom = X1, start = X2, end = X3, proportion = X7) |>
  mutate(feature = "ty1")

ty3 <- read_tsv(
  "../results/windows/Ty3.bed",
  comment = "#",
  col_names = FALSE
  ) |>
  select(chrom = X1, start = X2, end = X3, proportion = X7) |>
  mutate(feature = "ty3")

methylation <- read_tsv(
  "../results/windows/methylation.tab",
  comment = "#",
  col_names = FALSE
  ) |>
  select(
    chrom = X1,
    start = X2,
    end = X3,
    cg = X4,
    chg = X5,
    chh = X6
    ) |>
  pivot_longer(!chrom:end, names_to = "feature", values_to = "proportion")

features <- rbind(gc, genes, ty1, ty3, methylation) |>
  filter(str_detect(chrom, "chr"))
```

Plot assembly features

```{r}
plot <- ggplot(features) +
  geom_rect(aes(xmin = start, xmax = end, ymin = 0, ymax = proportion, fill = proportion)) +
  facet_grid(feature ~ chrom, scales = "free") +
  theme_bw(base_size = 8) +
  theme(
    panel.grid = element_blank(),
    legend.position = "none",
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank(),
    panel.spacing.x = unit(0, "lines")
    ) +
  scale_fill_viridis_c(option = "magma")

ggsave("plots/assembly.png", width = 5.9, height = 4, dpi = 600)
```