---
title: "Centromeres"
author: "Moray Smith"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggthemes)
library(ggnewscale)
library(ggpubr)
```

Plot centromeres

```{r}
df <- read_tsv("../results/windows/cen_methylation.tab", col_names = FALSE, comment = "#") |>
  group_by(X1) |>
  mutate(
    start = X2 - min(X2),
    end = X3 - min(X2),
    CENH = (X7 - min(X7))/(max(X7) - min(X7))
  ) |>
  select(chr = X1, start, end, CG = X4, CHG = X5, CHH = X6, CENH)

trash <- read_tsv("../results/windows/cen_TRASH.bed", col_names = FALSE) |>
  group_by(X1) |>
  mutate(start = X2 - min(X2), end = X3 - min(X2)) |>
  select(chr = X1, start, end, TRASH = X7)

ty3 <- read_tsv("../results/windows/cen_Ty3.bed", col_names = FALSE) |>
  group_by(X1) |>
  mutate(start = X2 - min(X2), end = X3 - min(X2)) |>
  select(chr = X1, start, end, Ty3 = X7)

df <- df |>
  left_join(trash, by = join_by(chr, start, end)) |>
  left_join(ty3, by = join_by(chr, start, end)) |>
  mutate(chr = str_replace(chr, "chr", "cen"))
  
plot <- ggplot(df) +
  geom_rect(aes(xmin = start, xmax = end, ymin = 0, ymax = 1, fill = CENH)) +
  scale_fill_gradient(low = "white", high = "#BAB0AC") +
  new_scale_fill() +
  geom_rect(aes(xmin = start, xmax = end, ymin = -0.25, ymax = 0, fill = TRASH)) +
  scale_fill_gradient(low = "white", high = "#76B7B2") +
  new_scale_fill() +
  geom_rect(aes(xmin = start, xmax = end, ymin = 1, ymax = 1.25, fill = Ty3)) +
  scale_fill_gradient(low = "white", high = "#59A14F") +
  geom_line(aes(x = start + (end - start), y = CG), colour = "#4E79A7") +
  geom_line(aes(x = start + (end - start), y = CHG), colour = "#F28E2B") +
  geom_line(aes(x = start + (end - start), y = CHH), colour = "#E15759") +
  facet_grid(chr ~ ., scales = "free_x") +
  theme_bw(base_size = 8) +
  theme(
    panel.grid = element_blank(),
    strip.text.y.right = element_text(angle = 0),
    legend.position = "none"
  ) +
  scale_x_continuous(label = scales::label_number(scale_cut = scales::cut_short_scale())) +
  labs(
    x = "Centromere length",
    y = "Mean methylation (proportion)"
  )

cowplot::ggsave2("plots/centromeres.png", plot, width = 5.9, height = 4, dpi = 600)
```

```{r}
tesorter <- read_tsv("../results/tesorter/earlgrey.cls.tsv") |>
  mutate(
    family = str_to_lower(
      str_extract(TE, "^(.*?)#(.*?)(?:/(.*))?$", group = 1)
      )
  )
```

```{r}
library(tidyverse)
library(ggpubr)
library(ggthemes)

calculate_fischer <- function(inside, outside, total_inside, total_outside) {
  # Create the contingency table
  contingency_table <- matrix(c(inside, total_inside - inside, outside, total_outside - outside), 
                              nrow = 2)
  
  # Perform Fisher's exact test
  fisher_test_result <- fisher.test(contingency_table)
  
  # Extract odds ratio and p-value
  odds_ratio <- fisher_test_result$estimate
  p_value <- fisher_test_result$p.value
  
  return(list(odds_ratio, p_value = p_value))
}
```

```{r}
earlgrey_gff <- read_tsv(
  "../results/earlgrey/solanum_verrucosum_summaryFiles/solanum_verrucosum.filteredRepeats.gff",
  col_names = FALSE,
  ) |>
  filter(!str_detect(X3, "Simple_repeat|Low_complexity")) |>
  filter(!str_detect(X1, "scaffold")) |>
  mutate(family = str_to_lower(str_extract(X9, "ID=(.*?);", group = 1))) |>
  dplyr::select(
    chrom = "X1",
    type = "X3",
    start = "X4",
    end = "X5",
    family
  )

centromere_bed <- read_tsv(
  "../results/cenh3/centromeres.bed",
  col_names = FALSE
  ) |>
  dplyr::select(
    chrom = "X1",
    cen_start = "X2",
    cen_end = "X3"
  )

earlgrey_gff <- earlgrey_gff |>
  left_join(centromere_bed, by = "chrom") |>
  mutate(
    cen_status = ifelse(start > cen_start & end < cen_end, "inside", "outside")
  )

count_table <- earlgrey_gff |>
  group_by(family, cen_status) |>
  count() |>
  pivot_wider(names_from = cen_status, values_from = n) %>% # lol
  replace(is.na(.), 0)

total_inside <- sum(count_table$inside)
total_outside <- sum(count_table$outside)

calc_fisher <- function(inside, outside, total_inside, total_outside) {
  contingency_table <- matrix(
    c(inside, total_inside - inside, outside, total_outside - outside), 
    nrow = 2
    )
  
  result <- fisher.test(contingency_table)
  return(list(result$p.value, result$estimate))
}

count_table <- count_table |>
  mutate(
    p.value = calc_fisher(inside, outside, total_inside, total_outside)[[1]],
    odds = calc_fisher(inside, outside, total_inside, total_outside)[[2]],
    )
```

```{r}
count_table |>
  filter(p.value < 0.001) |>
  ggplot(aes(x = log10(odds))) +
  geom_histogram(bins = 200) +
  theme_bw(base_size = 8) + theme(panel.grid = element_blank()) +
  scale_fill_tableau()
```
Use odds ratio > 10 as cutoff for interesting families

```{r}
count_table |>
  filter(p.value < 0.001 & odds >= 10)
```
## CENH3 enrichment

```{r}
earlgrey_cenh3 <- read_csv("../results/earlgrey_cenh3_summary.csv") |>
  filter(str_detect(ID, "RND")) |>
  mutate(family = str_to_lower(ID)) |>
  dplyr::select(family, mean_cenh3 = sum)
```

```{r}
te_cenh3_hist <- earlgrey_cenh3 |>
  left_join(tesorter, by = "family") |>
  filter(Order == "LTR") |>
  ggplot() +
  geom_histogram(aes(x = mean_cenh3, fill = Superfamily), bins = 50) +
  xlab("Mean CENH3 read depth") +
  ylab("# LTR families") +
  theme_bw(base_size = 8) + theme(panel.grid = element_blank()) +
  scale_fill_tableau()

te_cenh3_hist
```

```{r}
te_cenh3_point <- earlgrey_cenh3 |>
  left_join(count_table, by = "family") |>
  left_join(tesorter, by = "family") |>
  filter(Order == "LTR") |>
  mutate(
    highlighted = case_when (
      Clade == "Tekay" ~ "Tekay",
      Clade == "CRM" ~ "CRM",
      .default = "Other"
    )
  ) |> 
  ggplot() +
  geom_point(aes(x = log10(odds), y = mean_cenh3, colour = highlighted)) +
  xlab("Log10(Odds ratio)") +
  ylab("Mean CENH3 read depth") +
  theme_bw(base_size = 8) + theme(panel.grid = element_blank()) +
  scale_colour_tableau(name = "Clade", breaks = c("CRM", "Tekay", "Other"))

te_cenh3_point
```

```{r}
ggsave(
  "plots/te_cenh3.png",
  ggarrange(
    te_cenh3_hist + theme(legend.position = "bottom"),
    te_cenh3_point + theme(legend.position = "bottom"),
    ncol = 2,
    align = "hv",
    labels = "auto",
    font.label = list(size = 10)
  ),
  width = 5.9,
  height = 3,
  dpi = 600
)
```