---
title: "Centromeres"
author: "Moray Smith"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(ggtree)
library(ggthemes)
library(extrafont)
library(scattermore)
font_import(prompt = FALSE, pattern = "arial")
loadfonts(device = "win")

theme_set(theme_bw(base_size = 8, base_family = "Arial") + theme(panel.grid = element_blank()))
```

```{r}
cg <- read_tsv("../results/centromeres/centromere_window_CG.bed", col_names = FALSE) |>
  select(chromosome = X1, start = X2, end = X3, CG = X4) |>
  group_by(chromosome) |>
  mutate(end = end - min(start),start = start - min(start))

chg <- read_tsv("../results/centromeres/centromere_window_CHG.bed", col_names = FALSE) |>
  select(chromosome = X1, start = X2, end = X3, CHG = X4) |>
  group_by(chromosome) |>
  mutate(end = end - min(start),start = start - min(start))

chh <- read_tsv("../results/centromeres/centromere_window_CHH.bed", col_names = FALSE) |>
  select(chromosome = X1, start = X2, end = X3, CHH = X4) |>
  group_by(chromosome) |>
  mutate(end = end - min(start),start = start - min(start))

ty3 <- read_tsv("../results/centromeres/centromere_window_ty3.bed", col_names = FALSE) |>
  select(chromosome = X1, start = X2, end = X3, Ty3 = X4) |>
  group_by(chromosome) |>
  mutate(end = end - min(start),start = start - min(start))

trash <- read_tsv("../results/centromeres/centromere_window_trash.bed", col_names = FALSE) |>
  select(chromosome = X1, start = X2, end = X3, TRASH = X4) |>
  group_by(chromosome) |>
  mutate(start = start - min(start), end = end - min(start))

cenh3 <- read_tsv(
  "../results/centromeres/centromere_window_cenh3.tab",
  col_names = FALSE,
  comment = "#"
) |>
  group_by(X1) |>
  mutate(
    CENH3 = (X4 - min(X4))/(max(X4) - min(X4))
  ) |>
  select(chromosome = X1, start = X2, end = X3, CENH3) |>
  group_by(chromosome) |>
  mutate(end = end - min(start), start = start - min(start))

merged <- cg |>
  left_join(chg, by = join_by(chromosome, start, end)) |>
  left_join(chh, by = join_by(chromosome, start, end)) |>
  left_join(ty3, by = join_by(chromosome, start, end)) |>
  left_join(trash, by = join_by(chromosome, start, end)) |>
  left_join(cenh3, by = join_by(chromosome, start, end))

ggplot(merged) +
  geom_rect(aes(xmin = start, xmax = end, ymin = 0, ymax = 1, fill = CG)) +
  scale_fill_gradient(low = "white", high = "#BAB0AC") +
  facet_grid(chromosome ~ ., scales = "free_x")
```
```{r}
# import te classifications accoridng to tesorter
tesorter <- read_tsv("../results/tesorter/earlgrey.cls.tsv", skip = 1, col_names = FALSE) |>
  mutate(family = str_to_lower(str_extract(X1, "(rnd-\\d_family-\\d+).*", group = 1))) |>
  select(order = X2, superfamily = X3, clade = X4, family)

# get earlgrey annotations and their positions
earlgrey <- read_tsv(
  "../results/solanum_verrucosum.filteredRepeats.gff", col_names = FALSE
) |>
  filter(!str_detect(X3, "Simple_repeat|Low_complexity")) |>
  filter(!str_detect(X1, "scaffold")) |>
  mutate(family = str_to_lower(str_extract(X9, "ID=(.*?);", group = 1))) |>
  dplyr::select(
    chromosome = X1,
    type = X3,
    start = X4,
    end = X5,
    family
  )

# get centromere positions and join them to earlgrey, identifying if TE lies inside or outside
centromere_positions <- read_tsv(
  "../results/centromeres/centromere_positions.bed",
  col_names = FALSE
) |>
  select(chromosome = X1, cen_start = X2, cen_end = X3)

earlgrey <- earlgrey|>
  left_join(centromere_positions, by = "chromosome") |>
  mutate(
    cen_status = ifelse(start > cen_start & end < cen_end, "inside", "outside")
  )

# create a table of these counts for each family
count_table <- earlgrey |>
  group_by(family, cen_status) |>
  count() |>
  pivot_wider(names_from = cen_status, values_from = n) %>%
  replace(is.na(.), 0)

# values for contingency
total_inside <- sum(count_table$inside)
total_outside <- sum(count_table$outside)

# MATHS!
count_table <- count_table |>
  inner_join(tesorter) |>
  rowwise() |>
  mutate(
    fisher = list(fisher.test(matrix(c(inside, outside, total_inside - inside, total_outside - outside), nrow = 2))),
    p_value = fisher$p.value,
    odds = fisher$estimate
  )

count_table |>
  inner_join(tesorter) |>
  filter(p_value < 0.05) |>
  ggplot(aes(x = odds, fill = clade)) +
  geom_histogram() +
  scale_x_log10()

unusual <- count_table |>
  inner_join(tesorter) |>
  filter(p_value < 0.001) |>
  pull(family)
```

```{r}
tree <- read.tree("../results/tesorter/earlgrey.cls.pep.RT.aln.parstree")
tree$tip.label <- str_extract(tree$tip.label,pattern = "(rnd-\\d_family-\\d+)_.*", group = 1)

plot <- ggtree(tree) %<+% count_table

plot +
  geom_tiplab(align = TRUE, size = 1) +
  geom_tippoint(aes(colour = odds))

plot2 <- ggtree(tidytree::tree_subset(tree, node = "rnd-1_family-236", levels_back = 5)) %<+% count_table
plot2 <- plot2 +
  geom_tippoint(aes(colour = clade)) +
  geom_treescale() +
  scale_colour_tableau()

odds <- count_table |>
  select(family, odds) |>
  column_to_rownames("family")

plot2 <- gheatmap(plot2, odds, color = NA, width = .1) +
  scale_fill_viridis_c(option = "magma")
  
ggsave("plots/centromere_tes.svg", plot2, width = 100, height = 100, units = "mm")
```
